# Download test data from: https://osf.io/tn4xj/

model_path: "D:/3D U-Net/pytorch-3dunet/CHECKPOINT_DIR/best_checkpoint.pytorch"
model:
  name: ResidualUNet3D
  # number of input channels to the model
  in_channels: 1
  # number of output channels
  out_channels: 1
  # determines the order of operators in a single layer (crg - Conv3d+ReLU+GroupNorm)
  layer_order: gcr
  # initial number of feature maps
  f_maps: 32
  # number of groups in the groupnorm
  num_groups: 8
  # apply element-wise nn.Sigmoid after the final 1x1x1 convolution, otherwise apply nn.Softmax
  final_sigmoid: true
predictor:
  name: 'StandardPredictor'
loaders:
  # save predictions to output_dir
  output_dir: "D:/3D U-Net/pytorch-3dunet/result/3_27"
  # batch dimension; if number of GPUs is N > 1, then a batch_size of N * batch_size will automatically be taken for DataParallel
  batch_size: 1
  # how many subprocesses to use for data loading
  num_workers: 8
  # test loaders configuration
  test:
    file_paths:
      - "D:/3D U-Net/pytorch-3dunet/dataset/test"

    slice_builder:
      name: SliceBuilder
      patch_shape: [32, 64, 64]
      stride_shape: [32, 64, 64]
      # halo around each patch
      halo_shape: [ 0, 0, 0 ]

    transformer:
      raw:
        - name: Standardize
        - name: ToTensor
          expand_dims: true
